---------------------------------------
-- TABLE USERS
---------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE
);

---------------------------------------
-- TABLE REQUESTS
---------------------------------------
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(512) NOT NULL,
    requestor_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,

    CONSTRAINT requests_users_fk
        FOREIGN KEY (requestor_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

---------------------------------------
-- TABLE ITEMS
---------------------------------------
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    request_id BIGINT DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    available BOOLEAN NOT NULL,

    CONSTRAINT items_users_fk
        FOREIGN KEY (owner_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT items_requests_fk
        FOREIGN KEY (request_id)
        REFERENCES requests(id)
        ON DELETE SET NULL
);

---------------------------------------
-- TABLE BOOKINGS
---------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR(10) DEFAULT 'WAITING' NOT NULL,

    CONSTRAINT bookings_users_fk
        FOREIGN KEY (booker_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT bookings_items_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON DELETE CASCADE
);

---------------------------------------
-- TABLE COMMENTS
---------------------------------------
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comments_text VARCHAR(512) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,

    CONSTRAINT comments_items_fk
        FOREIGN KEY (item_id)
        REFERENCES items(id)
        ON DELETE CASCADE,

    CONSTRAINT comments_users_fk
        FOREIGN KEY (author_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);